name: CI Process

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker Compose
        id: docker_run
        # Use continue-on-error so we can create the fail artifact even if tests fail
        continue-on-error: true 
        run: docker compose up --build --exit-code-from test_runner

      # Based on the test result: publish artifacts
      - name: Publish Success Artifact
        if: steps.docker_run.outcome == 'success'
        run: |
          echo "Tests passed successfully" > succeeded
          mkdir -p results && mv succeeded results/

      - name: Publish Failure Artifact
        if: steps.docker_run.outcome == 'failure'
        run: |
          echo "Tests failed" > failed
          mkdir -p results && mv failed results/

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/
